title: Dhanny Indrakusuma # your name (or website title) here
logo: "/images/dhanny tumblr.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Fashion Designer learning to code
  <br><br>
  Based in Jakarta, Indonesia
  <br><br>
  <a href="https://www.linkedin.com/in/dindrakusuma/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
